name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install rollup
        run: npm i -g rollup

      - name: install app dependencies
        run: npm run install-dependencies
        
      - name: tempfix link issue (linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: rm -rf /home/runner/work/node/node/app/node_modules/tiny-secp256k1/build/node_gyp_bins/python3

      - name: tempfix link issue (mac)
        if: ${{ matrix.os == 'macos-latest' }}
        run: rm -rf /Users/runner/work/node/node/app/node_modules/tiny-secp256k1/build/node_gyp_bins/python3

      - name: build app
        run: npm run build

      uses: actions/upload-artifact@v3
        # with:
        path: build/*.*
        # uses: VandeurenGlenn/action-electron-kit@v1.1.1
        # with:
        #   # GitHub token, automatically provided to the action
        #   # (No need to define this secret in the repo settings)
        #   github_token: ${{ secrets.github_token }}

        #   # If the commit is tagged with a version (e.g. "v1.0.0"),
        #   # release the app after building
        #   release: ${{ startsWith(github.ref, 'refs/tags/v') }}
